// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"lisp_lambda-go/internal/core/datamodels"
	"lisp_lambda-go/internal/evaluator/internal"
	"sync"
)

type FakeQuoteFunctionEvaluator struct {
	EvaluateQuoteFunctionStub        func(datamodels.ProgramItem, datamodels.NodeStack, datamodels.ProgramItemStack)
	evaluateQuoteFunctionMutex       sync.RWMutex
	evaluateQuoteFunctionArgsForCall []struct {
		arg1 datamodels.ProgramItem
		arg2 datamodels.NodeStack
		arg3 datamodels.ProgramItemStack
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeQuoteFunctionEvaluator) EvaluateQuoteFunction(arg1 datamodels.ProgramItem, arg2 datamodels.NodeStack, arg3 datamodels.ProgramItemStack) {
	fake.evaluateQuoteFunctionMutex.Lock()
	fake.evaluateQuoteFunctionArgsForCall = append(fake.evaluateQuoteFunctionArgsForCall, struct {
		arg1 datamodels.ProgramItem
		arg2 datamodels.NodeStack
		arg3 datamodels.ProgramItemStack
	}{arg1, arg2, arg3})
	stub := fake.EvaluateQuoteFunctionStub
	fake.recordInvocation("EvaluateQuoteFunction", []interface{}{arg1, arg2, arg3})
	fake.evaluateQuoteFunctionMutex.Unlock()
	if stub != nil {
		fake.EvaluateQuoteFunctionStub(arg1, arg2, arg3)
	}
}

func (fake *FakeQuoteFunctionEvaluator) EvaluateQuoteFunctionCallCount() int {
	fake.evaluateQuoteFunctionMutex.RLock()
	defer fake.evaluateQuoteFunctionMutex.RUnlock()
	return len(fake.evaluateQuoteFunctionArgsForCall)
}

func (fake *FakeQuoteFunctionEvaluator) EvaluateQuoteFunctionCalls(stub func(datamodels.ProgramItem, datamodels.NodeStack, datamodels.ProgramItemStack)) {
	fake.evaluateQuoteFunctionMutex.Lock()
	defer fake.evaluateQuoteFunctionMutex.Unlock()
	fake.EvaluateQuoteFunctionStub = stub
}

func (fake *FakeQuoteFunctionEvaluator) EvaluateQuoteFunctionArgsForCall(i int) (datamodels.ProgramItem, datamodels.NodeStack, datamodels.ProgramItemStack) {
	fake.evaluateQuoteFunctionMutex.RLock()
	defer fake.evaluateQuoteFunctionMutex.RUnlock()
	argsForCall := fake.evaluateQuoteFunctionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeQuoteFunctionEvaluator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.evaluateQuoteFunctionMutex.RLock()
	defer fake.evaluateQuoteFunctionMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeQuoteFunctionEvaluator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ internal.QuoteFunctionEvaluator = new(FakeQuoteFunctionEvaluator)
