// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"lisp_lambda-go/internal/core/datamodels"
	"lisp_lambda-go/internal/evaluator/internal"
	"sync"
)

type FakeCondChildStackItemBuilder struct {
	BuildCondChildStackItemsStub        func(datamodels.ProgramItem, datamodels.ProgramItemStack)
	buildCondChildStackItemsMutex       sync.RWMutex
	buildCondChildStackItemsArgsForCall []struct {
		arg1 datamodels.ProgramItem
		arg2 datamodels.ProgramItemStack
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCondChildStackItemBuilder) BuildCondChildStackItems(arg1 datamodels.ProgramItem, arg2 datamodels.ProgramItemStack) {
	fake.buildCondChildStackItemsMutex.Lock()
	fake.buildCondChildStackItemsArgsForCall = append(fake.buildCondChildStackItemsArgsForCall, struct {
		arg1 datamodels.ProgramItem
		arg2 datamodels.ProgramItemStack
	}{arg1, arg2})
	stub := fake.BuildCondChildStackItemsStub
	fake.recordInvocation("BuildCondChildStackItems", []interface{}{arg1, arg2})
	fake.buildCondChildStackItemsMutex.Unlock()
	if stub != nil {
		fake.BuildCondChildStackItemsStub(arg1, arg2)
	}
}

func (fake *FakeCondChildStackItemBuilder) BuildCondChildStackItemsCallCount() int {
	fake.buildCondChildStackItemsMutex.RLock()
	defer fake.buildCondChildStackItemsMutex.RUnlock()
	return len(fake.buildCondChildStackItemsArgsForCall)
}

func (fake *FakeCondChildStackItemBuilder) BuildCondChildStackItemsCalls(stub func(datamodels.ProgramItem, datamodels.ProgramItemStack)) {
	fake.buildCondChildStackItemsMutex.Lock()
	defer fake.buildCondChildStackItemsMutex.Unlock()
	fake.BuildCondChildStackItemsStub = stub
}

func (fake *FakeCondChildStackItemBuilder) BuildCondChildStackItemsArgsForCall(i int) (datamodels.ProgramItem, datamodels.ProgramItemStack) {
	fake.buildCondChildStackItemsMutex.RLock()
	defer fake.buildCondChildStackItemsMutex.RUnlock()
	argsForCall := fake.buildCondChildStackItemsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCondChildStackItemBuilder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.buildCondChildStackItemsMutex.RLock()
	defer fake.buildCondChildStackItemsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCondChildStackItemBuilder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ internal.CondChildStackItemBuilder = new(FakeCondChildStackItemBuilder)
