// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"lisp_lambda-go/internal/core/datamodels"
	"lisp_lambda-go/internal/evaluator/internal"
	"sync"
)

type FakeTopProgramItemCreator struct {
	CreateTopProgramItemStub        func(datamodels.ExpressionListNode, map[string]datamodels.Node, datamodels.ProgramItemStack)
	createTopProgramItemMutex       sync.RWMutex
	createTopProgramItemArgsForCall []struct {
		arg1 datamodels.ExpressionListNode
		arg2 map[string]datamodels.Node
		arg3 datamodels.ProgramItemStack
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTopProgramItemCreator) CreateTopProgramItem(arg1 datamodels.ExpressionListNode, arg2 map[string]datamodels.Node, arg3 datamodels.ProgramItemStack) {
	fake.createTopProgramItemMutex.Lock()
	fake.createTopProgramItemArgsForCall = append(fake.createTopProgramItemArgsForCall, struct {
		arg1 datamodels.ExpressionListNode
		arg2 map[string]datamodels.Node
		arg3 datamodels.ProgramItemStack
	}{arg1, arg2, arg3})
	stub := fake.CreateTopProgramItemStub
	fake.recordInvocation("CreateTopProgramItem", []interface{}{arg1, arg2, arg3})
	fake.createTopProgramItemMutex.Unlock()
	if stub != nil {
		fake.CreateTopProgramItemStub(arg1, arg2, arg3)
	}
}

func (fake *FakeTopProgramItemCreator) CreateTopProgramItemCallCount() int {
	fake.createTopProgramItemMutex.RLock()
	defer fake.createTopProgramItemMutex.RUnlock()
	return len(fake.createTopProgramItemArgsForCall)
}

func (fake *FakeTopProgramItemCreator) CreateTopProgramItemCalls(stub func(datamodels.ExpressionListNode, map[string]datamodels.Node, datamodels.ProgramItemStack)) {
	fake.createTopProgramItemMutex.Lock()
	defer fake.createTopProgramItemMutex.Unlock()
	fake.CreateTopProgramItemStub = stub
}

func (fake *FakeTopProgramItemCreator) CreateTopProgramItemArgsForCall(i int) (datamodels.ExpressionListNode, map[string]datamodels.Node, datamodels.ProgramItemStack) {
	fake.createTopProgramItemMutex.RLock()
	defer fake.createTopProgramItemMutex.RUnlock()
	argsForCall := fake.createTopProgramItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTopProgramItemCreator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createTopProgramItemMutex.RLock()
	defer fake.createTopProgramItemMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTopProgramItemCreator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ internal.TopProgramItemCreator = new(FakeTopProgramItemCreator)
