// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"lisp_lambda-go/internal/core/datamodels"
	"lisp_lambda-go/internal/evaluator/internal"
	"sync"
)

type FakeStackUpdateDeterminer struct {
	DetermineHowToUpdateStacksStub        func(datamodels.Node, map[string]datamodels.Node, datamodels.NodeStack, datamodels.ProgramItemStack)
	determineHowToUpdateStacksMutex       sync.RWMutex
	determineHowToUpdateStacksArgsForCall []struct {
		arg1 datamodels.Node
		arg2 map[string]datamodels.Node
		arg3 datamodels.NodeStack
		arg4 datamodels.ProgramItemStack
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStackUpdateDeterminer) DetermineHowToUpdateStacks(arg1 datamodels.Node, arg2 map[string]datamodels.Node, arg3 datamodels.NodeStack, arg4 datamodels.ProgramItemStack) {
	fake.determineHowToUpdateStacksMutex.Lock()
	fake.determineHowToUpdateStacksArgsForCall = append(fake.determineHowToUpdateStacksArgsForCall, struct {
		arg1 datamodels.Node
		arg2 map[string]datamodels.Node
		arg3 datamodels.NodeStack
		arg4 datamodels.ProgramItemStack
	}{arg1, arg2, arg3, arg4})
	stub := fake.DetermineHowToUpdateStacksStub
	fake.recordInvocation("DetermineHowToUpdateStacks", []interface{}{arg1, arg2, arg3, arg4})
	fake.determineHowToUpdateStacksMutex.Unlock()
	if stub != nil {
		fake.DetermineHowToUpdateStacksStub(arg1, arg2, arg3, arg4)
	}
}

func (fake *FakeStackUpdateDeterminer) DetermineHowToUpdateStacksCallCount() int {
	fake.determineHowToUpdateStacksMutex.RLock()
	defer fake.determineHowToUpdateStacksMutex.RUnlock()
	return len(fake.determineHowToUpdateStacksArgsForCall)
}

func (fake *FakeStackUpdateDeterminer) DetermineHowToUpdateStacksCalls(stub func(datamodels.Node, map[string]datamodels.Node, datamodels.NodeStack, datamodels.ProgramItemStack)) {
	fake.determineHowToUpdateStacksMutex.Lock()
	defer fake.determineHowToUpdateStacksMutex.Unlock()
	fake.DetermineHowToUpdateStacksStub = stub
}

func (fake *FakeStackUpdateDeterminer) DetermineHowToUpdateStacksArgsForCall(i int) (datamodels.Node, map[string]datamodels.Node, datamodels.NodeStack, datamodels.ProgramItemStack) {
	fake.determineHowToUpdateStacksMutex.RLock()
	defer fake.determineHowToUpdateStacksMutex.RUnlock()
	argsForCall := fake.determineHowToUpdateStacksArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeStackUpdateDeterminer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.determineHowToUpdateStacksMutex.RLock()
	defer fake.determineHowToUpdateStacksMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStackUpdateDeterminer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ internal.StackUpdateDeterminer = new(FakeStackUpdateDeterminer)
