// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"lisp_lambda-go/internal/core/datamodels"
	"lisp_lambda-go/internal/evaluator/internal"
	"sync"
)

type FakeRootNodeEvaluator struct {
	EvaluateStub        func(datamodels.ExpressionListNode, map[string]datamodels.DefunFunction, datamodels.ProgramItemStack, datamodels.NodeStack) (datamodels.Node, error)
	evaluateMutex       sync.RWMutex
	evaluateArgsForCall []struct {
		arg1 datamodels.ExpressionListNode
		arg2 map[string]datamodels.DefunFunction
		arg3 datamodels.ProgramItemStack
		arg4 datamodels.NodeStack
	}
	evaluateReturns struct {
		result1 datamodels.Node
		result2 error
	}
	evaluateReturnsOnCall map[int]struct {
		result1 datamodels.Node
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRootNodeEvaluator) Evaluate(arg1 datamodels.ExpressionListNode, arg2 map[string]datamodels.DefunFunction, arg3 datamodels.ProgramItemStack, arg4 datamodels.NodeStack) (datamodels.Node, error) {
	fake.evaluateMutex.Lock()
	ret, specificReturn := fake.evaluateReturnsOnCall[len(fake.evaluateArgsForCall)]
	fake.evaluateArgsForCall = append(fake.evaluateArgsForCall, struct {
		arg1 datamodels.ExpressionListNode
		arg2 map[string]datamodels.DefunFunction
		arg3 datamodels.ProgramItemStack
		arg4 datamodels.NodeStack
	}{arg1, arg2, arg3, arg4})
	stub := fake.EvaluateStub
	fakeReturns := fake.evaluateReturns
	fake.recordInvocation("Evaluate", []interface{}{arg1, arg2, arg3, arg4})
	fake.evaluateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRootNodeEvaluator) EvaluateCallCount() int {
	fake.evaluateMutex.RLock()
	defer fake.evaluateMutex.RUnlock()
	return len(fake.evaluateArgsForCall)
}

func (fake *FakeRootNodeEvaluator) EvaluateCalls(stub func(datamodels.ExpressionListNode, map[string]datamodels.DefunFunction, datamodels.ProgramItemStack, datamodels.NodeStack) (datamodels.Node, error)) {
	fake.evaluateMutex.Lock()
	defer fake.evaluateMutex.Unlock()
	fake.EvaluateStub = stub
}

func (fake *FakeRootNodeEvaluator) EvaluateArgsForCall(i int) (datamodels.ExpressionListNode, map[string]datamodels.DefunFunction, datamodels.ProgramItemStack, datamodels.NodeStack) {
	fake.evaluateMutex.RLock()
	defer fake.evaluateMutex.RUnlock()
	argsForCall := fake.evaluateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeRootNodeEvaluator) EvaluateReturns(result1 datamodels.Node, result2 error) {
	fake.evaluateMutex.Lock()
	defer fake.evaluateMutex.Unlock()
	fake.EvaluateStub = nil
	fake.evaluateReturns = struct {
		result1 datamodels.Node
		result2 error
	}{result1, result2}
}

func (fake *FakeRootNodeEvaluator) EvaluateReturnsOnCall(i int, result1 datamodels.Node, result2 error) {
	fake.evaluateMutex.Lock()
	defer fake.evaluateMutex.Unlock()
	fake.EvaluateStub = nil
	if fake.evaluateReturnsOnCall == nil {
		fake.evaluateReturnsOnCall = make(map[int]struct {
			result1 datamodels.Node
			result2 error
		})
	}
	fake.evaluateReturnsOnCall[i] = struct {
		result1 datamodels.Node
		result2 error
	}{result1, result2}
}

func (fake *FakeRootNodeEvaluator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.evaluateMutex.RLock()
	defer fake.evaluateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRootNodeEvaluator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ internal.RootNodeEvaluator = new(FakeRootNodeEvaluator)
